from django.db import models

# Create your models here.

class Habit(models.Model):
    habit = models.CharField(max_length=200) 
    created = models.DateTimeField(auto_now_add=True)
    day_1 = models.BooleanField(default=False)
    day_2 = models.BooleanField(default=False)
    day_3 = models.BooleanField(default=False)
    day_4 = models.BooleanField(default=False)
    day_5 = models.BooleanField(default=False)
    day_6 = models.BooleanField(default=False)
    day_7 = models.BooleanField(default=False)
    day_8 = models.BooleanField(default=False)
    day_9 = models.BooleanField(default=False)
    day_10 = models.BooleanField(default=False)
    day_11 = models.BooleanField(default=False)
    day_12 = models.BooleanField(default=False)
    day_13 = models.BooleanField(default=False)
    day_14 = models.BooleanField(default=False)
    day_15 = models.BooleanField(default=False)
    day_16 = models.BooleanField(default=False)
    day_17 = models.BooleanField(default=False)
    day_18 = models.BooleanField(default=False)
    day_19 = models.BooleanField(default=False)
    day_20 = models.BooleanField(default=False)
    day_21 = models.BooleanField(default=False)
    day_22 = models.BooleanField(default=False)
    day_23 = models.BooleanField(default=False)
    day_24 = models.BooleanField(default=False)
    day_25 = models.BooleanField(default=False)
    day_26 = models.BooleanField(default=False)
    day_27 = models.BooleanField(default=False)
    day_28 = models.BooleanField(default=False)
    day_29 = models.BooleanField(default=False)
    day_30 = models.BooleanField(default=False)
    day_31 = models.BooleanField(default=False)
    day_32 = models.BooleanField(default=False)
    day_33 = models.BooleanField(default=False)
    day_34 = models.BooleanField(default=False)
    day_35 = models.BooleanField(default=False)
    day_36 = models.BooleanField(default=False)
    day_37 = models.BooleanField(default=False)
    day_38 = models.BooleanField(default=False)
    day_39 = models.BooleanField(default=False)
    day_40 = models.BooleanField(default=False)
    day_41 = models.BooleanField(default=False)
    day_42 = models.BooleanField(default=False)
    day_43 = models.BooleanField(default=False)
    day_44 = models.BooleanField(default=False)
    day_45 = models.BooleanField(default=False)
    day_46 = models.BooleanField(default=False)
    day_47 = models.BooleanField(default=False)
    day_48 = models.BooleanField(default=False)
    day_49 = models.BooleanField(default=False)
    day_50 = models.BooleanField(default=False)

    def __str__(self):
        days_status = ', '.join([f"day_{i}: {getattr(self, f'day_{i}')}" for i in range(1, 51)])
        return f"Habit: {self.habit}, Created: {self.created}, Days: {days_status}"
